In [1]:
import numpy as np
import random
#Make Distmat
distmat = np.zeros([12,12]);
for i in range(12):
    for j in range(12):
        distmat[i][j] = abs(i-j);

distmat[distmat>6]  = 6-abs(6-distmat[distmat>6])
print(distmat)


[[0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0.]]


In [2]:
#Make PrintChord
def printChord(chord):
    notenames = ['A','A#','B','C','C#','D','D#','E','F','F#','G','G#']
    if len(chord) == 1:
        root = chord[0];
        rest = '';
    elif chord[1]=='#':
        root = chord[:2];
        rest = chord[2:];
    else:
        root = chord[0];
        rest = chord[1:];
    #major chord
    if rest == '':
        note2 = notenames[np.mod(notenames.index(root)+3+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note4 = root;
        note1= root;
    #minor chord
    elif 'm'==rest:
        note2 = notenames[np.mod(notenames.index(root)+2+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note4 = root;
        note1= root;
    #minor 7th chord
    elif 'm7'==rest:
        note2 = notenames[np.mod(notenames.index(root)+2+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+9+1,12)];
        note1= root;   
    #major 7th chord
    elif 'maj7'==rest:
        note2 = notenames[np.mod(notenames.index(root)+3+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+10+1,12)];
        note1= root;
    #dominant 7th chord
    elif '7'==rest:
        note2 = notenames[np.mod(notenames.index(root)+3+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+9+1,12)];
        note1= root;
    #dim chord
    elif 'dim'==rest:
        note2 = notenames[np.mod(notenames.index(root)+2+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+5+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+8+1,12)];
        note1= root;
    #6 chord
    elif '6'==rest:
        note2 = notenames[np.mod(notenames.index(root)+3+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+8+1,12)];
        note1= root;
    #69 chord
    elif '69'==rest:
        note2 = notenames[np.mod(notenames.index(root)+3+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+8+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+13+1,12)];
        note1= root;
    #aug chord
    elif 'aug'==rest:
        note2 = notenames[np.mod(notenames.index(root)+3+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+7+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+11+1,12)];
        note1= root;
    #m6 chord
    elif 'm6'==rest:
        note2 = notenames[np.mod(notenames.index(root)+2+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+8+1,12)];
        note1= root;
    #9 chord
    elif '9'==rest:
        note2 = notenames[np.mod(notenames.index(root)+3+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+9+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+13+1,12)];
        note1= root;
    #sus chord
    elif 'sus'==rest:
        note2 = notenames[np.mod(notenames.index(root)+4+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+11+1,12)];
        note1= root;
    #sus2 chord
    elif 'sus2'==rest:
        note2 = notenames[np.mod(notenames.index(root)+1+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+11+1,12)];
        note1= root;
    #add2 chord
    elif 'add2'==rest:
        note2 = notenames[np.mod(notenames.index(root)+1+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+3+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note1= root;    
    #minmaj chord
    elif 'minmaj'==rest:
        note2 = notenames[np.mod(notenames.index(root)+2+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+6+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+10+1,12)];
        note1= root;
    #m9 chord
    elif 'm9'==rest:
        note2 = notenames[np.mod(notenames.index(root)+2+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+9+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+13+1,12)];
        note1= root;
    #maj9 chord
    elif 'maj9'==rest:
        note2 = notenames[np.mod(notenames.index(root)+3+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+10+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+13+1,12)];
        note1= root;
    #m11 chord
    elif 'm11'==rest:
        note2 = notenames[np.mod(notenames.index(root)+2+1,12)];
        note3 = notenames[np.mod(notenames.index(root)+9+1,12)];
        note4 = notenames[np.mod(notenames.index(root)+16+1,12)];
        note1= root;
    else:
        print(chord)
        asdsadln
    return([note1,note2,note3,note4]);


In [3]:
#Find the chord distance
import itertools

def chorddist(chord1,chord2,distmat):
    notenames = ['A','A#','B','C','C#','D','D#','E','F','F#','G','G#'];
    P = list(itertools.permutations(chord2))
    minD = 10000;
    for ii in range(len(P)):  

        distance = 0;
        for i in range(len(chord1)):
            #print(notenames.index(P[ii][i]))
            #print(notenames.index(chord1[i]))
            distance = distance + distmat[notenames.index(chord1[i])][notenames.index(P[ii][i])];
        if distance < minD:
            minD = distance;
    dist = minD
    return dist

In [4]:
def getTransMatrix(set1,set2,distmat):
    transMat = np.zeros([len(set1),len(set2)]);
    for i in range(len(set1)):
        for j in range(len(set2)):
            chord1 = printChord(set1[i]);
            chord2 = printChord(set2[j]);
            transMat[i,j] = chorddist(chord1,chord2,distmat);
    return transMat

In [5]:

A9 = printChord('A7')
D9 = printChord('D')
print(A9)
print(D9)
print(chorddist(A9,D9,distmat))

c = []
d = []
e = []
f = []
g = []
a = []
b = []

['A', 'C#', 'E', 'G']
['D', 'F#', 'A', 'D']
4.0


In [6]:
notes = {}
#Commented out a few chords with #s
#Set the chords

notes['c'] = ['C','Cmaj7','C6','C69','F','Fmaj7','F6','Am','Am7','Csus2','Csus','Gsus',\
            'D7','Fm','C#maj7','D#6','F#dim','C7','G#maj7','A#add2','Cm'];
notes['d'] = ['Dm7','Em7','G','G7','Cmaj9','Cadd2','Gsus','Dm','Dm6','F6',\
            'E7','Fm6','A#','A#7','A#6','C9','Ddim','D7','D6','D'];
notes['e'] = ['C','Cmaj7','C6','C69','G6','Fmaj7','Am','Am7','Em','Em7',\
            'Fminmaj','D9','A','A7','E7','A9','C7','E','Em9'];
notes['f'] = ['F','Fmaj7','Dm','Dm7','G7','Bdim','F','Csus',\
            'Fdim','A#','A#7','Fm','Fm6','Fm7','D#m9','D#9'];
notes['g'] = ['C','Cmaj7','C6','Am7','Csus2','Csus','G','G7','G9','Gsus','Em','Em7','Dm11',\
            'Edim','D#','C7','D#6','A7','Fm9','A#6','C7','C9','Gaug'];
notes['a'] = ['F','Fmaj7','Dm','Dm7','Am','Am7','C6','G9', \
            'B7','A7','D7','Adim','F7'];#,'C13'];
notes['b'] = ['Em','Em7','G','G6','G7','Bdim','Am9',\
              #,'G13',
            'B','Bdim','Gaug','B7','E7','C#7','A9'];


In [7]:
print(len(notes['c']))
print(len(notes['b']))

21
14


In [8]:
#Find the raw transitions quickly

if 'transmat' not in locals() and 'transmat' not in globals():
    transmat = {}
    alphabet = 'abcdefg'
    for i in alphabet:
        for j in alphabet:
            transmat[str(i)+str(j)] = getTransMatrix(notes[i],notes[j],distmat)

print(transmat['aa'])
natnotenames = [x for x in alphabet]
print(natnotenames)


[[0. 1. 5. 3. 5. 3. 3. 3. 4. 4. 4. 3. 2.]
 [1. 0. 4. 2. 4. 2. 2. 4. 3. 3. 3. 2. 1.]
 [5. 4. 0. 2. 8. 6. 6. 8. 5. 5. 3. 4. 3.]
 [3. 2. 2. 0. 6. 4. 4. 6. 3. 5. 1. 2. 1.]
 [5. 4. 8. 6. 0. 2. 2. 4. 5. 3. 5. 4. 5.]
 [3. 2. 6. 4. 2. 0. 0. 2. 3. 1. 3. 2. 3.]
 [3. 2. 6. 4. 2. 0. 0. 2. 3. 1. 3. 2. 3.]
 [3. 4. 8. 6. 4. 2. 2. 0. 3. 3. 5. 4. 5.]
 [4. 3. 5. 3. 5. 3. 3. 3. 0. 4. 2. 1. 2.]
 [4. 3. 5. 5. 3. 1. 1. 3. 4. 0. 4. 3. 4.]
 [4. 3. 3. 1. 5. 3. 3. 5. 2. 4. 0. 1. 2.]
 [3. 2. 4. 2. 4. 2. 2. 4. 1. 3. 1. 0. 1.]
 [2. 1. 3. 1. 5. 3. 3. 5. 2. 4. 2. 1. 0.]]
['a', 'b', 'c', 'd', 'e', 'f', 'g']


In [40]:
mel_note = []
harm = []
prompt = 'Put in a natural note that you would like to be the melody note: '
print(prompt)
x = input();

while str(x) not in alphabet:
    x = input();

print(x)
mel_note.append(x)
melodyind = np.random.randint(0,7);

#Melodyind override
melodyind = alphabet.index(x);
melodynote = natnotenames[melodyind];
harmonyind = random.choice(range(len(notes[str(melodynote)])));
harmonyclass = notes[str(melodynote)];
harmony = harmonyclass[harmonyind]
print('Starting chord: '+harmony)
harm.append(harmony) 
#print(harmonyind)
y = 'y';

Put in a natural note that you would like to be the melody note: 
a
a
Starting chord: B7


In [10]:
#Choose shortest path
while y=='y':
    #Change this to adjust for voiceleading
    print(prompt)
    x = input();
    while str(x) not in alphabet:
        print(prompt)
        x = input();
    mel_note.append(x) 
    nextnoteind = np.random.randint(0,7);
    nextnoteind = alphabet.index(x)

    nextnote = natnotenames[nextnoteind]
    nextharmonyclass = notes[str(nextnote)];

    transition = nextnote+melodynote;


    #print(transition)
    
    #This should be right now!
    #print(transmat[str(transition)])
    
    M = np.min(transmat[str(transition)],0);
    I = np.argmin(transmat[str(transition)],axis=0)
    '''
    print(I)
    print(M)
    print(melodynote)
    print(nextnote)
    print(harmonyind)
    print(harmony)
    print(I[harmonyind])
    print(M[harmonyind])
    '''
    nextnoteharmony = nextharmonyclass[I[harmonyind]]
    print('Next chord: '+nextnoteharmony)
    harm.append(nextnoteharmony) 
    harmonyind = I[harmonyind];
    melodynote = nextnote;
    harmonyclass = nextharmonyclass;
    harmony = nextnoteharmony;
    melodyind = nextnoteind;
    print('Do you want to keep going? Type y for continuing, anything else for not: ')
    y = input()

Put in a natural note that you would like to be the melody note: 
b
Next chord: Em7
Do you want to keep going? Type y for continuing, anything else for not: 
y
Put in a natural note that you would like to be the melody note: 
c
Next chord: Cmaj7
Do you want to keep going? Type y for continuing, anything else for not: 
y
Put in a natural note that you would like to be the melody note: 
e
Next chord: Cmaj7
Do you want to keep going? Type y for continuing, anything else for not: 
y
Put in a natural note that you would like to be the melody note: 
d
Next chord: Em7
Do you want to keep going? Type y for continuing, anything else for not: 
y
Put in a natural note that you would like to be the melody note: 
f
Next chord: G7
Do you want to keep going? Type y for continuing, anything else for not: 
y
Put in a natural note that you would like to be the melody note: 
b
Next chord: G7
Do you want to keep going? Type y for continuing, anything else for not: 
y
Put in a natural note that you would l

In [41]:
#Set temperature
print('Choose a temperature from 0 to 10')
inp = float(input())
while inp > 10 or inp < 0:
    print('Choose a temperature from 0 to 10')
    inp = float(input())
inp = inp-5
temp = np.exp(inp)
print(temp)
y = 'y'
while y=='y':
    #Change this to adjust for voiceleading
    print(prompt)
    x = input();
    while str(x) not in alphabet:
        print(prompt)
        x = input();
    mel_note.append(x) 
    nextnoteind = np.random.randint(0,7);
    nextnoteind = alphabet.index(x)

    nextnote = natnotenames[nextnoteind]
    nextharmonyclass = notes[str(nextnote)];

    transition = nextnote+melodynote;


    #print(transition)
    
    #This should be right now!
    #print(transmat[str(transition)])
    temp_trans_mat = np.reciprocal(transmat[str(transition)]+1.0)
    temp_trans_mat = np.power(temp_trans_mat,temp)
    #print(temp_trans_mat)
    temp_trans_mat = temp_trans_mat / temp_trans_mat.sum(axis=0)
    #print(temp_trans_mat)
    I = []
    for i in range(temp_trans_mat.shape[1]):
        '''
        print(len(temp_trans_mat[:]))
        print(i)
        print(temp_trans_mat[:,i])
        '''
        I.append(random.choices(range(temp_trans_mat.shape[0]), weights = temp_trans_mat[:,i])[0])
    print(I)
    '''
    print(I)
    print(M)
    print(melodynote)
    print(nextnote)
    print(harmonyind)
    print(harmony)
    print(I[harmonyind])
    print(M[harmonyind])
    '''
    nextnoteharmony = nextharmonyclass[I[harmonyind]]
    print('Next chord: '+nextnoteharmony)
    harm.append(nextnoteharmony)
    harmonyind = I[harmonyind];
    melodynote = nextnote;
    harmonyclass = nextharmonyclass;
    harmony = nextnoteharmony;
    melodyind = nextnoteind;
    print('Do you want to keep going? Type y for continuing, anything else for not: ')
    y = input()



Choose a temperature from 0 to 10
5
1.0
Put in a natural note that you would like to be the melody note: 
c
[10, 19, 3, 3, 10, 17, 10, 11, 8, 4, 6, 17, 8]
Next chord: Am7
Do you want to keep going? Type y for continuing, anything else for not: 
y
Put in a natural note that you would like to be the melody note: 
e
[0, 10, 16, 2, 10, 11, 5, 17, 13, 13, 3, 0, 6, 15, 12, 18, 6, 11, 8, 17, 13]
Next chord: A7
Do you want to keep going? Type y for continuing, anything else for not: 
y
Put in a natural note that you would like to be the melody note: 
f
[7, 6, 0, 1, 2, 12, 4, 1, 12, 11, 12, 1, 5, 13, 4, 0, 13, 13, 13]
Next chord: Fm7
Do you want to keep going? Type y for continuing, anything else for not: 
y
Put in a natural note that you would like to be the melody note: 
a
[3, 1, 5, 6, 10, 11, 1, 7, 10, 1, 5, 12, 11, 12, 11, 2]
Next chord: F7
Do you want to keep going? Type y for continuing, anything else for not: 
y
Put in a natural note that you would like to be the melody note: 
e
[17, 5, 

In [42]:
#Print mel_note and harm
print(mel_note)
print(harm)

['a', 'c', 'e', 'f', 'a', 'e', 'g']
['B7', 'Am7', 'A7', 'Fm7', 'F7', 'C69', 'Gaug']


In [ ]:
#Reset
del mel_note
del harm